name: Build

concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: src

      - name: Checkout Builds
        uses: actions/checkout@v5
        with:
          ref: builds
          path: builds

      - name: Setup JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build Plugins
        run: |
          cd "$GITHUB_WORKSPACE/src"

          chmod +x gradlew
          ./gradlew make generateUpdaterJson

          cp plugins/*/build/outputs/*.zip build/outputs/updater.json "$GITHUB_WORKSPACE/builds"

      - name: Push Builds
        run: |
          cd "$GITHUB_WORKSPACE/builds"

          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push
